### ISSUE TITLE
LocalGameBuild not working if UnrealFolder contains a space

### ISSUE THREAD

**Issue by FlooflesDev** [Al-Dente-Software/Tortellini#2]
I got the error `'C:\Program' is not recognized as an internal or external command,
operable program or batch file.` with UE installed under `C:\Program Files (x86)\Unreal\UE_5.3`.

I managed to fix this locally by moving some of the quotation marks in build.ps1. I will make a Pull Request with these changes later.

I'm pretty new to powershell scripts, so please do double-check if my changes also work for you :)

**Comment by brasky** [comment]
@FlooflesDev This is awesome thank you!
